from xg_tdx_func.xg_tdx_func import *
from trader_tool.unification_data import unification_data
class trend_king_v2_subchart:
    def __init__(self,df=''):
        '''
        趋势王v2副图
        '''
        self.df=df
    def trend_king_v2_subchart(self):
        '''
        A1赋值:((开盘价+最高价+最低价+收盘价)/4的3日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的6日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的9日指数移动平均)/3
        A2赋值:((开盘价+最高价+最低价+收盘价)/4的5日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的10日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的20日指数移动平均)/3
        A3赋值:((开盘价+最高价+最低价+收盘价)/4的7日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的14日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的28日指数移动平均)/3
        A4赋值:((开盘价+最高价+最低价+收盘价)/4的9日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的18日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的36日指数移动平均)/3
        A5赋值:((开盘价+最高价+最低价+收盘价)/4的11日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的22日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的44日指数移动平均)/3
        A6赋值:((开盘价+最高价+最低价+收盘价)/4的13日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的26日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的52日指数移动平均)/3
        A7赋值:((开盘价+最高价+最低价+收盘价)/4的21日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的34日指数移动平均+(开盘价+最高价+最低价+收盘价)/4的68日指数移动平均)/3
        ABC1赋值:A1的6日线性回归预测值
        ABC2赋值:A2的6日线性回归预测值
        ABC3赋值:A3的6日线性回归预测值
        ABC4赋值:A4的6日线性回归预测值
        ABC5赋值:A5的6日线性回归预测值
        ABC6赋值:A6的6日线性回归预测值
        ABC7赋值:A7的6日线性回归预测值
        如果ABC1>1日前的ABC1,返回ABC1,否则返回无效数,POINTDOT,COLORFF00FF
        如果ABC1<1日前的ABC1,返回ABC1,否则返回无效数,POINTDOT,COLOR00FF00
        如果ABC2>1日前的ABC2,返回ABC2,否则返回无效数,POINTDOT,COLORFF00FF
        如果ABC2<1日前的ABC2,返回ABC2,否则返回无效数,POINTDOT,COLOR00FF00
        如果ABC3>1日前的ABC3,返回ABC3,否则返回无效数,POINTDOT,COLORFF00FF
        如果ABC3<1日前的ABC3,返回ABC3,否则返回无效数,POINTDOT,COLOR00FF00
        如果ABC4>1日前的ABC4,返回ABC4,否则返回无效数,POINTDOT,COLORFF00FF
        如果ABC4<1日前的ABC4,返回ABC4,否则返回无效数,POINTDOT,COLOR00FF00
        如果ABC5>1日前的ABC5,返回ABC5,否则返回无效数,POINTDOT,COLORFF00FF
        如果ABC5<1日前的ABC5,返回ABC5,否则返回无效数,POINTDOT,COLOR00FF00
        如果ABC6>1日前的ABC6,返回ABC6,否则返回无效数,POINTDOT,COLORFF00FF
        如果ABC6<1日前的ABC6,返回ABC6,否则返回无效数,POINTDOT,COLOR00FF00
        如果ABC7>1日前的ABC7,返回ABC7,否则返回无效数,线宽为2,画红色
        如果ABC7<1日前的ABC7,返回ABC7,否则返回无效数,线宽为2,COLOR00FF00
        尊重市场赋值:(3*收盘价+2*开盘价+最高价+最低价)/7的3日指数移动平均的6日线性回归预测值
        DIRECTIONMAX赋值:1日前的尊重市场和1日前的尊重市场的较大值
        DIRECTIONMIN赋值:1日前的尊重市场和1日前的尊重市场的较小值
        当满足条件尊重市场>=1日前的尊重市场时,在尊重市场和DIRECTIONMAX位置之间画柱状线,宽度为4,0不为0则画空心柱.,画黄色
        当满足条件尊重市场<1日前的尊重市场时,在尊重市场和DIRECTIONMIN位置之间画柱状线,宽度为4,0不为0则画空心柱.,COLOR00FF00
        '''
        df=self.df
        CLOSE=df['close']
        C=df['close']
        LOW=df['low']
        L=df['low']
        low=df['low']
        HIGH=df['high']
        H=df['high']
        OPEN=df['open']
        O=df['open']
        volume=df['volume']
        V=df['volume']
        A1=(EMA((OPEN+HIGH+LOW+CLOSE)/4,3)+EMA((OPEN+HIGH+LOW+CLOSE)/4,6)+EMA((OPEN+HIGH+LOW+CLOSE)/4,9))/3
        A2=(EMA((OPEN+HIGH+LOW+CLOSE)/4,5)+EMA((OPEN+HIGH+LOW+CLOSE)/4,10)+EMA((OPEN+HIGH+LOW+CLOSE)/4,20))/3
        A3=(EMA((OPEN+HIGH+LOW+CLOSE)/4,7)+EMA((OPEN+HIGH+LOW+CLOSE)/4,14)+EMA((OPEN+HIGH+LOW+CLOSE)/4,28))/3
        A4=(EMA((OPEN+HIGH+LOW+CLOSE)/4,9)+EMA((OPEN+HIGH+LOW+CLOSE)/4,18)+EMA((OPEN+HIGH+LOW+CLOSE)/4,36))/3
        A5=(EMA((OPEN+HIGH+LOW+CLOSE)/4,11)+EMA((OPEN+HIGH+LOW+CLOSE)/4,22)+EMA((OPEN+HIGH+LOW+CLOSE)/4,44))/3
        A6=(EMA((OPEN+HIGH+LOW+CLOSE)/4,13)+EMA((OPEN+HIGH+LOW+CLOSE)/4,26)+EMA((OPEN+HIGH+LOW+CLOSE)/4,52))/3
        A7=(EMA((OPEN+HIGH+LOW+CLOSE)/4,21)+EMA((OPEN+HIGH+LOW+CLOSE)/4,34)+EMA((OPEN+HIGH+LOW+CLOSE)/4,68))/3
        ABC1=FORCAST(A1,6)
        ABC2=FORCAST(A2,6)
        ABC3=FORCAST(A3,6)
        ABC4=FORCAST(A4,6)
        ABC5=FORCAST(A5,6)
        ABC6=FORCAST(A6,6)
        ABC7=FORCAST(A7,6)
        '''
        IF(ABC1>REF(ABC1,1),ABC1,None),POINTDOT,COLORFF00FF;
        IF(ABC1<REF(ABC1,1),ABC1,None),POINTDOT,COLOR00FF00;
        IF(ABC2>REF(ABC2,1),ABC2,None),POINTDOT,COLORFF00FF;
        IF(ABC2<REF(ABC2,1),ABC2,None),POINTDOT,COLOR00FF00;
        IF(ABC3>REF(ABC3,1),ABC3,None),POINTDOT,COLORFF00FF;
        IF(ABC3<REF(ABC3,1),ABC3,None),POINTDOT,COLOR00FF00;
        IF(ABC4>REF(ABC4,1),ABC4,None),POINTDOT,COLORFF00FF;
        IF(ABC4<REF(ABC4,1),ABC4,None),POINTDOT,COLOR00FF00;
        IF(ABC5>REF(ABC5,1),ABC5,None),POINTDOT,COLORFF00FF;
        IF(ABC5<REF(ABC5,1),ABC5,None),POINTDOT,COLOR00FF00;
        IF(ABC6>REF(ABC6,1),ABC6,None),POINTDOT,COLORFF00FF;
        IF(ABC6<REF(ABC6,1),ABC6,None),POINTDOT,COLOR00FF00;
        '''
        '''
        IF(ABC7>REF(ABC7,1),ABC7,None),LINETHICK2,COLORRED;
        IF(ABC7<REF(ABC7,1),ABC7,None),LINETHICK2,COLOR00FF00;
        '''
        df['趋势线']=IF(ABC7>REF(ABC7,1),'红色',"绿色")
        尊重市场=FORCAST(EMA((3*CLOSE+2*OPEN+HIGH+LOW)/7,3),6)
        DIRECTIONMAX=MAX(REF(尊重市场,1),REF(尊重市场,1))
        DIRECTIONMIN=MIN(REF(尊重市场,1),REF(尊重市场,1))
        '''
        STICKLINE(尊重市场>=REF(尊重市场,1),尊重市场,DIRECTIONMAX,4,0),COLORYELLOW;
        STICKLINE(尊重市场<REF(尊重市场,1),尊重市场,DIRECTIONMIN,4,0),COLOR00FF00;
        '''
        df['方块']=IF(尊重市场>=REF(尊重市场,1),"黄色","绿色")
        return df
if __name__=='__main__':
    data=unification_data(trader_tool='ths')
    data=data.get_unification_data()
    df=data.get_hist_data_em(stock='159920')
    modes=trend_king_v2_subchart(df=df)
    result=modes.trend_king_v2_subchart()
    print(result)
    result.to_excel(r'数据.xlsx')