# Generated by Django 5.1.7 on 2025-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtfSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("new_price", models.FloatField(verbose_name="最新价")),
                ("change_rate", models.FloatField(verbose_name="涨跌幅")),
                ("ups_downs", models.FloatField(verbose_name="涨跌额")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                ("deal_amount", models.BigIntegerField(verbose_name="成交额")),
                ("open_price", models.FloatField(verbose_name="开盘价")),
                ("high_price", models.FloatField(verbose_name="最高价")),
                ("low_price", models.FloatField(verbose_name="最低价")),
                ("pre_close_price", models.FloatField(verbose_name="昨收")),
                ("turnoverrate", models.FloatField(verbose_name="换手率")),
                ("total_market_cap", models.BigIntegerField(verbose_name="总市值")),
                ("free_cap", models.BigIntegerField(verbose_name="流通市值")),
            ],
            options={
                "verbose_name": "每日ETF数据",
                "verbose_name_plural": "每日ETF数据",
                "db_table": "cn_etf_spot",
            },
        ),
        migrations.CreateModel(
            name="StockAttention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
            ],
            options={
                "verbose_name": "我的关注",
                "verbose_name_plural": "我的关注",
                "db_table": "cn_stock_attention",
            },
        ),
        migrations.CreateModel(
            name="StockBlocktrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("new_price", models.FloatField(verbose_name="收盘价")),
                ("change_rate", models.FloatField(verbose_name="涨跌幅")),
                ("average_price", models.FloatField(verbose_name="成交均价")),
                ("overflow_rate", models.FloatField(verbose_name="折溢率")),
                ("trade_number", models.FloatField(verbose_name="成交笔数")),
                ("sum_volume", models.FloatField(verbose_name="成交总量")),
                ("sum_turnover", models.FloatField(verbose_name="成交总额")),
                (
                    "turnover_market_rate",
                    models.FloatField(verbose_name="成交占比流通市值"),
                ),
            ],
            options={
                "verbose_name": "股票大宗交易",
                "verbose_name_plural": "股票大宗交易",
                "db_table": "cn_stock_blocktrade",
            },
        ),
        migrations.CreateModel(
            name="StockBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                (
                    "convertible_total_rate",
                    models.FloatField(verbose_name="送转股份-送转总比例"),
                ),
                (
                    "convertible_rate",
                    models.FloatField(verbose_name="送转股份-送转比例"),
                ),
                (
                    "convertible_transfer_rate",
                    models.FloatField(verbose_name="送转股份-转股比例"),
                ),
                (
                    "bonusaward_rate",
                    models.FloatField(verbose_name="现金分红-现金分红比例"),
                ),
                ("bonusaward_yield", models.FloatField(verbose_name="现金分红-股息率")),
                ("basic_eps", models.FloatField(verbose_name="每股收益")),
                ("bvps", models.FloatField(verbose_name="每股净资产")),
                ("per_capital_reserve", models.FloatField(verbose_name="每股公积金")),
                (
                    "per_unassign_profit",
                    models.FloatField(verbose_name="每股未分配利润"),
                ),
                (
                    "netprofit_yoy_ratio",
                    models.FloatField(verbose_name="净利润同比增长"),
                ),
                ("total_shares", models.BigIntegerField(verbose_name="总股本")),
                ("plan_date", models.DateField(verbose_name="预案公告日")),
                ("record_date", models.DateField(verbose_name="股权登记日")),
                ("ex_dividend_date", models.DateField(verbose_name="除权除息日")),
                ("progress", models.CharField(max_length=50, verbose_name="方案进度")),
                ("report_date", models.DateField(verbose_name="最新公告日期")),
            ],
            options={
                "verbose_name": "股票分红配送",
                "verbose_name_plural": "股票分红配送",
                "db_table": "cn_stock_bonus",
            },
        ),
        migrations.CreateModel(
            name="StockChipRaceEnd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("new_price", models.FloatField(verbose_name="最新价")),
                ("change_rate", models.FloatField(verbose_name="涨跌幅")),
                ("pre_close_price", models.FloatField(verbose_name="昨收")),
                ("open_price", models.FloatField(verbose_name="今开")),
                ("deal_amount", models.BigIntegerField(verbose_name="收盘金额")),
                ("bid_rate", models.FloatField(verbose_name="抢筹幅度")),
                (
                    "bid_trust_amount",
                    models.BigIntegerField(verbose_name="抢筹委托金额"),
                ),
                (
                    "bid_deal_amount",
                    models.BigIntegerField(verbose_name="抢筹成交金额"),
                ),
                ("bid_ratio", models.FloatField(verbose_name="抢筹占比")),
            ],
            options={
                "verbose_name": "尾盘抢筹数据",
                "verbose_name_plural": "尾盘抢筹数据",
                "db_table": "cn_stock_chip_race_end",
            },
        ),
        migrations.CreateModel(
            name="StockChipRaceOpen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("new_price", models.FloatField(verbose_name="最新价")),
                ("change_rate", models.FloatField(verbose_name="涨跌幅")),
                ("pre_close_price", models.FloatField(verbose_name="昨收")),
                ("open_price", models.FloatField(verbose_name="今开")),
                ("deal_amount", models.BigIntegerField(verbose_name="开盘金额")),
                ("bid_rate", models.FloatField(verbose_name="抢筹幅度")),
                (
                    "bid_trust_amount",
                    models.BigIntegerField(verbose_name="抢筹委托金额"),
                ),
                (
                    "bid_deal_amount",
                    models.BigIntegerField(verbose_name="抢筹成交金额"),
                ),
                ("bid_ratio", models.FloatField(verbose_name="抢筹占比")),
            ],
            options={
                "verbose_name": "早盘抢筹数据",
                "verbose_name_plural": "早盘抢筹数据",
                "db_table": "cn_stock_chip_race_open",
            },
        ),
        migrations.CreateModel(
            name="StockFundFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("new_price", models.FloatField(verbose_name="最新价")),
                ("change_rate", models.FloatField(verbose_name="今日涨跌幅")),
                (
                    "fund_amount",
                    models.BigIntegerField(verbose_name="今日主力净流入-净额"),
                ),
                ("fund_rate", models.FloatField(verbose_name="今日主力净流入-净占比")),
                (
                    "fund_amount_super",
                    models.BigIntegerField(verbose_name="今日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super",
                    models.FloatField(verbose_name="今日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large",
                    models.BigIntegerField(verbose_name="今日大单净流入-净额"),
                ),
                (
                    "fund_rate_large",
                    models.FloatField(verbose_name="今日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium",
                    models.BigIntegerField(verbose_name="今日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium",
                    models.FloatField(verbose_name="今日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small",
                    models.BigIntegerField(verbose_name="今日小单净流入-净额"),
                ),
                (
                    "fund_rate_small",
                    models.FloatField(verbose_name="今日小单净流入-净占比"),
                ),
                ("change_rate_3", models.FloatField(verbose_name="3日涨跌幅")),
                (
                    "fund_amount_3",
                    models.BigIntegerField(verbose_name="3日主力净流入-净额"),
                ),
                ("fund_rate_3", models.FloatField(verbose_name="3日主力净流入-净占比")),
                (
                    "fund_amount_super_3",
                    models.BigIntegerField(verbose_name="3日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super_3",
                    models.FloatField(verbose_name="3日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large_3",
                    models.BigIntegerField(verbose_name="3日大单净流入-净额"),
                ),
                (
                    "fund_rate_large_3",
                    models.FloatField(verbose_name="3日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium_3",
                    models.BigIntegerField(verbose_name="3日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium_3",
                    models.FloatField(verbose_name="3日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small_3",
                    models.BigIntegerField(verbose_name="3日小单净流入-净额"),
                ),
                (
                    "fund_rate_small_3",
                    models.FloatField(verbose_name="3日小单净流入-净占比"),
                ),
                ("change_rate_5", models.FloatField(verbose_name="5日涨跌幅")),
                (
                    "fund_amount_5",
                    models.BigIntegerField(verbose_name="5日主力净流入-净额"),
                ),
                ("fund_rate_5", models.FloatField(verbose_name="5日主力净流入-净占比")),
                (
                    "fund_amount_super_5",
                    models.BigIntegerField(verbose_name="5日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super_5",
                    models.FloatField(verbose_name="5日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large_5",
                    models.BigIntegerField(verbose_name="5日大单净流入-净额"),
                ),
                (
                    "fund_rate_large_5",
                    models.FloatField(verbose_name="5日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium_5",
                    models.BigIntegerField(verbose_name="5日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium_5",
                    models.FloatField(verbose_name="5日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small_5",
                    models.BigIntegerField(verbose_name="5日小单净流入-净额"),
                ),
                (
                    "fund_rate_small_5",
                    models.FloatField(verbose_name="5日小单净流入-净占比"),
                ),
                ("change_rate_10", models.FloatField(verbose_name="10日涨跌幅")),
                (
                    "fund_amount_10",
                    models.BigIntegerField(verbose_name="10日主力净流入-净额"),
                ),
                (
                    "fund_rate_10",
                    models.FloatField(verbose_name="10日主力净流入-净占比"),
                ),
                (
                    "fund_amount_super_10",
                    models.BigIntegerField(verbose_name="10日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super_10",
                    models.FloatField(verbose_name="10日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large_10",
                    models.BigIntegerField(verbose_name="10日大单净流入-净额"),
                ),
                (
                    "fund_rate_large_10",
                    models.FloatField(verbose_name="10日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium_10",
                    models.BigIntegerField(verbose_name="10日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium_10",
                    models.FloatField(verbose_name="10日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small_10",
                    models.BigIntegerField(verbose_name="10日小单净流入-净额"),
                ),
                (
                    "fund_rate_small_10",
                    models.FloatField(verbose_name="10日小单净流入-净占比"),
                ),
            ],
            options={
                "verbose_name": "股票资金流向",
                "verbose_name_plural": "股票资金流向",
                "db_table": "cn_stock_fund_flow",
            },
        ),
        migrations.CreateModel(
            name="StockFundFlowConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("name", models.CharField(max_length=30, verbose_name="名称")),
                ("change_rate", models.FloatField(verbose_name="今日涨跌幅")),
                (
                    "fund_amount",
                    models.BigIntegerField(verbose_name="今日主力净流入-净额"),
                ),
                ("fund_rate", models.FloatField(verbose_name="今日主力净流入-净占比")),
                (
                    "fund_amount_super",
                    models.BigIntegerField(verbose_name="今日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super",
                    models.FloatField(verbose_name="今日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large",
                    models.BigIntegerField(verbose_name="今日大单净流入-净额"),
                ),
                (
                    "fund_rate_large",
                    models.FloatField(verbose_name="今日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium",
                    models.BigIntegerField(verbose_name="今日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium",
                    models.FloatField(verbose_name="今日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small",
                    models.BigIntegerField(verbose_name="今日小单净流入-净额"),
                ),
                (
                    "fund_rate_small",
                    models.FloatField(verbose_name="今日小单净流入-净占比"),
                ),
                (
                    "stock_name",
                    models.CharField(
                        max_length=20, verbose_name="今日主力净流入最大股"
                    ),
                ),
                ("change_rate_5", models.FloatField(verbose_name="5日涨跌幅")),
                (
                    "fund_amount_5",
                    models.BigIntegerField(verbose_name="5日主力净流入-净额"),
                ),
                ("fund_rate_5", models.FloatField(verbose_name="5日主力净流入-净占比")),
                (
                    "fund_amount_super_5",
                    models.BigIntegerField(verbose_name="5日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super_5",
                    models.FloatField(verbose_name="5日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large_5",
                    models.BigIntegerField(verbose_name="5日大单净流入-净额"),
                ),
                (
                    "fund_rate_large_5",
                    models.FloatField(verbose_name="5日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium_5",
                    models.BigIntegerField(verbose_name="5日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium_5",
                    models.FloatField(verbose_name="5日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small_5",
                    models.BigIntegerField(verbose_name="5日小单净流入-净额"),
                ),
                (
                    "fund_rate_small_5",
                    models.FloatField(verbose_name="5日小单净流入-净占比"),
                ),
                (
                    "stock_name_5",
                    models.CharField(max_length=20, verbose_name="5日主力净流入最大股"),
                ),
                ("change_rate_10", models.FloatField(verbose_name="10日涨跌幅")),
                (
                    "fund_amount_10",
                    models.BigIntegerField(verbose_name="10日主力净流入-净额"),
                ),
                (
                    "fund_rate_10",
                    models.FloatField(verbose_name="10日主力净流入-净占比"),
                ),
                (
                    "fund_amount_super_10",
                    models.BigIntegerField(verbose_name="10日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super_10",
                    models.FloatField(verbose_name="10日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large_10",
                    models.BigIntegerField(verbose_name="10日大单净流入-净额"),
                ),
                (
                    "fund_rate_large_10",
                    models.FloatField(verbose_name="10日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium_10",
                    models.BigIntegerField(verbose_name="10日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium_10",
                    models.FloatField(verbose_name="10日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small_10",
                    models.BigIntegerField(verbose_name="10日小单净流入-净额"),
                ),
                (
                    "fund_rate_small_10",
                    models.FloatField(verbose_name="10日小单净流入-净占比"),
                ),
                (
                    "stock_name_10",
                    models.CharField(
                        max_length=20, verbose_name="10日主力净流入最大股"
                    ),
                ),
            ],
            options={
                "verbose_name": "概念资金流向",
                "verbose_name_plural": "概念资金流向",
                "db_table": "cn_stock_fund_flow_concept",
            },
        ),
        migrations.CreateModel(
            name="StockFundFlowIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("name", models.CharField(max_length=30, verbose_name="名称")),
                ("change_rate", models.FloatField(verbose_name="今日涨跌幅")),
                (
                    "fund_amount",
                    models.BigIntegerField(verbose_name="今日主力净流入-净额"),
                ),
                ("fund_rate", models.FloatField(verbose_name="今日主力净流入-净占比")),
                (
                    "fund_amount_super",
                    models.BigIntegerField(verbose_name="今日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super",
                    models.FloatField(verbose_name="今日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large",
                    models.BigIntegerField(verbose_name="今日大单净流入-净额"),
                ),
                (
                    "fund_rate_large",
                    models.FloatField(verbose_name="今日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium",
                    models.BigIntegerField(verbose_name="今日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium",
                    models.FloatField(verbose_name="今日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small",
                    models.BigIntegerField(verbose_name="今日小单净流入-净额"),
                ),
                (
                    "fund_rate_small",
                    models.FloatField(verbose_name="今日小单净流入-净占比"),
                ),
                (
                    "stock_name",
                    models.CharField(
                        max_length=20, verbose_name="今日主力净流入最大股"
                    ),
                ),
                ("change_rate_5", models.FloatField(verbose_name="5日涨跌幅")),
                (
                    "fund_amount_5",
                    models.BigIntegerField(verbose_name="5日主力净流入-净额"),
                ),
                ("fund_rate_5", models.FloatField(verbose_name="5日主力净流入-净占比")),
                (
                    "fund_amount_super_5",
                    models.BigIntegerField(verbose_name="5日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super_5",
                    models.FloatField(verbose_name="5日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large_5",
                    models.BigIntegerField(verbose_name="5日大单净流入-净额"),
                ),
                (
                    "fund_rate_large_5",
                    models.FloatField(verbose_name="5日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium_5",
                    models.BigIntegerField(verbose_name="5日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium_5",
                    models.FloatField(verbose_name="5日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small_5",
                    models.BigIntegerField(verbose_name="5日小单净流入-净额"),
                ),
                (
                    "fund_rate_small_5",
                    models.FloatField(verbose_name="5日小单净流入-净占比"),
                ),
                (
                    "stock_name_5",
                    models.CharField(max_length=20, verbose_name="5日主力净流入最大股"),
                ),
                ("change_rate_10", models.FloatField(verbose_name="10日涨跌幅")),
                (
                    "fund_amount_10",
                    models.BigIntegerField(verbose_name="10日主力净流入-净额"),
                ),
                (
                    "fund_rate_10",
                    models.FloatField(verbose_name="10日主力净流入-净占比"),
                ),
                (
                    "fund_amount_super_10",
                    models.BigIntegerField(verbose_name="10日超大单净流入-净额"),
                ),
                (
                    "fund_rate_super_10",
                    models.FloatField(verbose_name="10日超大单净流入-净占比"),
                ),
                (
                    "fund_amount_large_10",
                    models.BigIntegerField(verbose_name="10日大单净流入-净额"),
                ),
                (
                    "fund_rate_large_10",
                    models.FloatField(verbose_name="10日大单净流入-净占比"),
                ),
                (
                    "fund_amount_medium_10",
                    models.BigIntegerField(verbose_name="10日中单净流入-净额"),
                ),
                (
                    "fund_rate_medium_10",
                    models.FloatField(verbose_name="10日中单净流入-净占比"),
                ),
                (
                    "fund_amount_small_10",
                    models.BigIntegerField(verbose_name="10日小单净流入-净额"),
                ),
                (
                    "fund_rate_small_10",
                    models.FloatField(verbose_name="10日小单净流入-净占比"),
                ),
                (
                    "stock_name_10",
                    models.CharField(
                        max_length=20, verbose_name="10日主力净流入最大股"
                    ),
                ),
            ],
            options={
                "verbose_name": "行业资金流向",
                "verbose_name_plural": "行业资金流向",
                "db_table": "cn_stock_fund_flow_industry",
            },
        ),
        migrations.CreateModel(
            name="StockLimitupReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("title", models.CharField(max_length=255, verbose_name="原因")),
                ("reason", models.CharField(max_length=2000, verbose_name="详因")),
                ("new_price", models.FloatField(verbose_name="最新价")),
                ("change_rate", models.FloatField(verbose_name="涨跌幅")),
                ("ups_downs", models.FloatField(verbose_name="涨跌额")),
                ("turnoverrate", models.FloatField(verbose_name="换手率")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                ("deal_amount", models.BigIntegerField(verbose_name="成交额")),
                ("dde", models.BigIntegerField(verbose_name="DDE")),
            ],
            options={
                "verbose_name": "涨停原因揭密",
                "verbose_name_plural": "涨停原因揭密",
                "db_table": "cn_stock_limitup_reason",
            },
        ),
        migrations.CreateModel(
            name="StockSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("new_price", models.FloatField(verbose_name="最新价")),
                ("change_rate", models.FloatField(verbose_name="涨跌幅")),
                ("ups_downs", models.FloatField(verbose_name="涨跌额")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                ("deal_amount", models.BigIntegerField(verbose_name="成交额")),
                ("amplitude", models.FloatField(verbose_name="振幅")),
                ("turnoverrate", models.FloatField(verbose_name="换手率")),
                ("volume_ratio", models.FloatField(verbose_name="量比")),
                ("open_price", models.FloatField(verbose_name="今开")),
                ("high_price", models.FloatField(verbose_name="最高")),
                ("low_price", models.FloatField(verbose_name="最低")),
                ("pre_close_price", models.FloatField(verbose_name="昨收")),
                ("speed_increase", models.FloatField(verbose_name="涨速")),
                ("speed_increase_5", models.FloatField(verbose_name="5分钟涨跌")),
                ("speed_increase_60", models.FloatField(verbose_name="60日涨跌幅")),
                (
                    "speed_increase_all",
                    models.FloatField(verbose_name="年初至今涨跌幅"),
                ),
                ("dtsyl", models.FloatField(verbose_name="市盈率动")),
                ("pe9", models.FloatField(verbose_name="市盈率TTM")),
                ("pe", models.FloatField(verbose_name="市盈率静")),
                ("pbnewmrq", models.FloatField(verbose_name="市净率")),
                ("basic_eps", models.FloatField(verbose_name="每股收益")),
                ("bvps", models.FloatField(verbose_name="每股净资产")),
                ("per_capital_reserve", models.FloatField(verbose_name="每股公积金")),
                (
                    "per_unassign_profit",
                    models.FloatField(verbose_name="每股未分配利润"),
                ),
                ("roe_weight", models.FloatField(verbose_name="加权净资产收益率")),
                ("sale_gpr", models.FloatField(verbose_name="毛利率")),
                ("debt_asset_ratio", models.FloatField(verbose_name="资产负债率")),
                (
                    "total_operate_income",
                    models.BigIntegerField(verbose_name="营业收入"),
                ),
                ("toi_yoy_ratio", models.FloatField(verbose_name="营业收入同比增长")),
                ("parent_netprofit", models.BigIntegerField(verbose_name="归属净利润")),
                (
                    "netprofit_yoy_ratio",
                    models.FloatField(verbose_name="归属净利润同比增长"),
                ),
                ("report_date", models.DateField(verbose_name="报告期")),
                ("total_shares", models.BigIntegerField(verbose_name="总股本")),
                ("free_shares", models.BigIntegerField(verbose_name="已流通股份")),
                ("total_market_cap", models.BigIntegerField(verbose_name="总市值")),
                ("free_cap", models.BigIntegerField(verbose_name="流通市值")),
                ("industry", models.CharField(max_length=20, verbose_name="所处行业")),
                ("listing_date", models.DateField(verbose_name="上市时间")),
            ],
            options={
                "verbose_name": "每日股票数据",
                "verbose_name_plural": "每日股票数据",
                "db_table": "cn_stock_spot",
            },
        ),
        migrations.CreateModel(
            name="StockSpotBuy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("new_price", models.FloatField(verbose_name="最新价")),
                ("change_rate", models.FloatField(verbose_name="涨跌幅")),
                ("ups_downs", models.FloatField(verbose_name="涨跌额")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                ("deal_amount", models.BigIntegerField(verbose_name="成交额")),
                ("amplitude", models.FloatField(verbose_name="振幅")),
                ("turnoverrate", models.FloatField(verbose_name="换手率")),
                ("volume_ratio", models.FloatField(verbose_name="量比")),
                ("open_price", models.FloatField(verbose_name="今开")),
                ("high_price", models.FloatField(verbose_name="最高")),
                ("low_price", models.FloatField(verbose_name="最低")),
                ("pre_close_price", models.FloatField(verbose_name="昨收")),
                ("speed_increase", models.FloatField(verbose_name="涨速")),
                ("speed_increase_5", models.FloatField(verbose_name="5分钟涨跌")),
                ("speed_increase_60", models.FloatField(verbose_name="60日涨跌幅")),
                (
                    "speed_increase_all",
                    models.FloatField(verbose_name="年初至今涨跌幅"),
                ),
                ("dtsyl", models.FloatField(verbose_name="市盈率动")),
                ("pe9", models.FloatField(verbose_name="市盈率TTM")),
                ("pe", models.FloatField(verbose_name="市盈率静")),
                ("pbnewmrq", models.FloatField(verbose_name="市净率")),
                ("basic_eps", models.FloatField(verbose_name="每股收益")),
                ("bvps", models.FloatField(verbose_name="每股净资产")),
                ("per_capital_reserve", models.FloatField(verbose_name="每股公积金")),
                (
                    "per_unassign_profit",
                    models.FloatField(verbose_name="每股未分配利润"),
                ),
                ("roe_weight", models.FloatField(verbose_name="加权净资产收益率")),
                ("sale_gpr", models.FloatField(verbose_name="毛利率")),
                ("debt_asset_ratio", models.FloatField(verbose_name="资产负债率")),
                (
                    "total_operate_income",
                    models.BigIntegerField(verbose_name="营业收入"),
                ),
                ("toi_yoy_ratio", models.FloatField(verbose_name="营业收入同比增长")),
                ("parent_netprofit", models.BigIntegerField(verbose_name="归属净利润")),
                (
                    "netprofit_yoy_ratio",
                    models.FloatField(verbose_name="归属净利润同比增长"),
                ),
                ("report_date", models.DateField(verbose_name="报告期")),
                ("total_shares", models.BigIntegerField(verbose_name="总股本")),
                ("free_shares", models.BigIntegerField(verbose_name="已流通股份")),
                ("total_market_cap", models.BigIntegerField(verbose_name="总市值")),
                ("free_cap", models.BigIntegerField(verbose_name="流通市值")),
                ("industry", models.CharField(max_length=20, verbose_name="所处行业")),
                ("listing_date", models.DateField(verbose_name="上市时间")),
            ],
            options={
                "verbose_name": "基本面选股",
                "verbose_name_plural": "基本面选股",
                "db_table": "cn_stock_spot_buy",
            },
        ),
        migrations.CreateModel(
            name="StockTop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("code", models.CharField(max_length=6, verbose_name="代码")),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("ranking_times", models.FloatField(verbose_name="上榜次数")),
                ("sum_buy", models.FloatField(verbose_name="累积购买额")),
                ("sum_sell", models.FloatField(verbose_name="累积卖出额")),
                ("net_amount", models.FloatField(verbose_name="净额")),
                ("buy_seat", models.FloatField(verbose_name="买入席位数")),
                ("sell_seat", models.FloatField(verbose_name="卖出席位数")),
            ],
            options={
                "verbose_name": "股票龙虎榜",
                "verbose_name_plural": "股票龙虎榜",
                "db_table": "cn_stock_top",
            },
        ),
    ]
