# Generated by Django 5.2.4 on 2025-08-05 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockmarket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="股票代码")),
                ("name", models.CharField(max_length=50, verbose_name="股票名称")),
            ],
            options={
                "verbose_name": "股票",
                "verbose_name_plural": "股票",
                "db_table": "stock",
            },
        ),
        migrations.AlterField(
            model_name="stockspot",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="etfspot",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockattention",
            unique_together={("datetime", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockblocktrade",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockbonus",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockchipraceend",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockchipraceopen",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockfundflow",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockfundflowconcept",
            unique_together={("date", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="stockfundflowindustry",
            unique_together={("date", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="stocklimitupreason",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stockspot",
            unique_together={("date", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stocktop",
            unique_together={("date", "code")},
        ),
        migrations.CreateModel(
            name="StockHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="时间")),
                ("date", models.DateField(verbose_name="日期")),
                ("symbol", models.CharField(max_length=10, verbose_name="股票代码")),
                ("open", models.FloatField(verbose_name="开盘价")),
                ("close", models.FloatField(verbose_name="收盘价")),
                ("high", models.FloatField(verbose_name="最高价")),
                ("low", models.FloatField(verbose_name="最低价")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                ("turnover", models.BigIntegerField(verbose_name="成交额")),
                ("amplitude", models.FloatField(verbose_name="振幅")),
                ("pct_change", models.FloatField(verbose_name="涨跌幅")),
                ("change", models.FloatField(verbose_name="涨跌额")),
                ("turnover_rate", models.FloatField(verbose_name="换手率")),
            ],
            options={
                "verbose_name": "股票历史数据",
                "verbose_name_plural": "股票历史数据",
                "db_table": "stock_history_data",
                "ordering": ["-date"],
                "unique_together": {("date", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="StockDailyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="开盘价"
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最高价"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最低价"
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="收盘价"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="前收盘价"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                (
                    "change_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="涨跌幅(%)"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额"
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="换手率(%)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="振幅(%)"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockmarket.stock",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "股票日线数据",
                "verbose_name_plural": "股票日线数据",
                "db_table": "stock_daily_data",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
