# Generated by Django 5.1.12 on 2026-08-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockmarket", "0002_stock_alter_stockspot_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="账户名称"
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[("A", "A股"), ("US", "美股")],
                        max_length=2,
                        verbose_name="市场",
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="币种")),
                (
                    "initial_cash",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="初始资金"
                    ),
                ),
                (
                    "cash",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="可用资金"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0003,
                        max_digits=10,
                        verbose_name="佣金率",
                    ),
                ),
                (
                    "slippage_bps",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        max_digits=8,
                        verbose_name="滑点基点",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "simulation_account",
            },
        ),
        migrations.CreateModel(
            name="SimulationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="股票代码")),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "买入"), ("SELL", "卖出")],
                        max_length=4,
                        verbose_name="方向",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("MARKET", "市价"), ("LIMIT", "限价")],
                        max_length=6,
                        verbose_name="订单类型",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "requested_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="委托价格",
                    ),
                ),
                (
                    "executed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="成交价格",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=20, verbose_name="佣金"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=20, verbose_name="税费"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待成交"),
                            ("FILLED", "已成交"),
                            ("REJECTED", "已拒绝"),
                        ],
                        default="PENDING",
                        max_length=8,
                        verbose_name="状态",
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=200, verbose_name="说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="stockmarket.simulationaccount",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="股票代码")),
                ("quantity", models.PositiveIntegerField(verbose_name="持仓数量")),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="平均成本"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="stockmarket.simulationaccount",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_position",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "symbol"), name="unique_simulation_position"
                    )
                ],
            },
        ),
    ]
