# Generated by Django 5.1.12 on 2026-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockmarket", "0003_simulationaccount_simulationorder_simulationposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=6, verbose_name="市场")),
                ("symbol", models.CharField(max_length=20, verbose_name="股票代码")),
                (
                    "strategy",
                    models.CharField(
                        default="sma_cross", max_length=40, verbose_name="策略"
                    ),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="参数")),
                ("start_date", models.DateField(verbose_name="起始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                ("total_return", models.FloatField(verbose_name="总收益率")),
                ("max_drawdown", models.FloatField(verbose_name="最大回撤")),
                ("sharpe_ratio", models.FloatField(verbose_name="夏普比率")),
                ("trade_count", models.PositiveIntegerField(verbose_name="成交次数")),
                ("trades", models.JSONField(default=list, verbose_name="模拟成交明细")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[("A", "A股"), ("US", "美股"), ("CRYPTO", "虚拟货币")],
                        max_length=6,
                        verbose_name="市场",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="股票代码")),
                (
                    "name",
                    models.CharField(blank=True, max_length=60, verbose_name="名称"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "watchlist_item",
                "ordering": ["market", "symbol"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "symbol"), name="unique_watchlist_symbol"
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="simulationaccount",
            name="market",
            field=models.CharField(
                choices=[("A", "A股"), ("US", "美股"), ("CRYPTO", "虚拟货币")],
                max_length=6,
                verbose_name="市场",
            ),
        ),
        migrations.AlterField(
            model_name="simulationorder",
            name="quantity",
            field=models.DecimalField(decimal_places=8, max_digits=24, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="simulationposition",
            name="quantity",
            field=models.DecimalField(decimal_places=8, max_digits=24, verbose_name="持仓数量"),
        ),
    ]
