# Generated by Django 5.1.12 on 2026-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockmarket", "0004_researchrun_watchlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationaccount",
            name="broker",
            field=models.CharField(
                choices=[
                    ("SIM", "内置模拟撮合"),
                    ("FUTU", "富途 OpenD"),
                    ("QMT", "迅投 QMT"),
                    ("IB", "盈透 IBKR"),
                ],
                default="SIM",
                max_length=10,
                verbose_name="券商通道",
            ),
        ),
        migrations.AddField(
            model_name="simulationaccount",
            name="broker_account_id",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="券商账号"
            ),
        ),
        migrations.AddField(
            model_name="simulationaccount",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最近同步"),
        ),
        migrations.AddField(
            model_name="simulationaccount",
            name="trading_mode",
            field=models.CharField(
                choices=[("PAPER", "模拟盘"), ("LIVE", "实盘")],
                default="PAPER",
                max_length=5,
                verbose_name="交易模式",
            ),
        ),
        migrations.AddField(
            model_name="simulationorder",
            name="broker_order_id",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="券商委托号"
            ),
        ),
        migrations.AddField(
            model_name="simulationorder",
            name="filled_quantity",
            field=models.DecimalField(
                decimal_places=8, default=0, max_digits=24, verbose_name="已成交数量"
            ),
        ),
        migrations.AlterField(
            model_name="simulationorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待成交"),
                    ("SUBMITTED", "已报"),
                    ("PARTIAL", "部分成交"),
                    ("FILLED", "已成交"),
                    ("CANCELLED", "已撤销"),
                    ("REJECTED", "已拒绝"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="状态",
            ),
        ),
    ]
